name: deploy-test-1

on:
  workflow_dispatch:
    inputs:
      tags:
        description: '배포할 서버'
        required: true
        type: choice
        default: 'all'
        options:
          - all
          - api
          - batch
          - crawler

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Print Tags
        run: |
          echo ${{ inputs.tags }} 

      - name: Print Secret
        run: echo ${{ secrets.TEST }}

  api:
    runs-on: ubuntu-latest
    if: >
      ${{ inputs.tags == 'all' || inputs.tags == 'api' }}

    steps:
      run: echo ${{ secrets.TEST }}
      - name: Print Secret

  batch:
    runs-on: ubuntu-latest
    if: >
      ${{ inputs.tags == 'all' || inputs.tags == 'batch' }}

    steps:
      run: echo ${{ secrets.TEST }}

  crawler:
    runs-on: ubuntu-latest
    if: >
      ${{ inputs.tags == 'all' || inputs.tags == 'crawler' }}

    steps:
      run: echo ${{ secrets.TEST }}
