#name: JDON-workflow-test
#
#on:
#  pull_request:
#    types: [ opened, closed ]
#    branches: [ develop ]
#
#jobs:
#  secret-test:
#    runs-on: ubuntu-latest
##    if: >
##      github.event.pull_request.merged == true &&
##      contains(join(github.event.pull_request.labels.*.name, ','), 'deploy-test')
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Print Branch Name
#        run: |
#          echo "Current branch: ${{ github.ref }}"
#
#  trigger-workflow:
#    runs-on: ubuntu-latest
#    if: >
#      github.event.pull_request.merged == true &&
#      contains(github.event.pull_request.labels.*.name, 'deploy-test')
#
#    steps:
#      - name: Trigger Other Workflow
#        uses: actions/github-script@v5
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          script: |
#            const response = await octokit.repos.createDispatchEvent({
#              owner: context.repo.owner,
#              repo: context.repo.repo,
#              event_type: 'trigger-other-workflow',
#              client_payload: {
#                foo: 'bar'
#              }
#            });
#            console.log(response);